export const environment = {
  BACKEND_CANISTER_ID: '<%= BACKEND_CANISTER_ID %>',
  FRONTEND_CANISTER_ID: '<%= FRONTEND_CANISTER_ID %>',
  INTERNET_IDENTITY_CANISTER_ID: '<%= INTERNET_IDENTITY_CANISTER_ID %>',
  DFX_NETWORK: '<%= DFX_NETWORK %>',
  DFX_HOST: '<%= DFX_HOST %>'
};